### ISSUE TITLE
Desktop.ini issue

### ISSUE THREAD

**Issue by SandyRis** [rileyzzz/BlenderIMExporter#1]
![image](https://user-images.githubusercontent.com/78733327/107213804-46ccaa00-6a09-11eb-8454-b5b68edb7640.png)
this issue happened when i exported a mesh with the 2.8+ exporter
if you know how to help me please respond

**Comment by rileyzzz** [comment]
This is a Trainz issue, and has nothing to do with the IM exporter - the only file types generated by the exporter are .im and .kin. Please only submit issues relating to the IM exporter - this isn't for general Trainz content creation help!
