### ISSUE TITLE
"IndexError: List Index out of range"

### ISSUE THREAD

**Issue by Semajic** [rileyzzz/BlenderIMExporter#10]
There seems to be a polygon limit on exporting meshes. When exporting a cube, everything works properly, however when trying to export a custom headlight mesh it gives a range error. When the polygon count is reduced and the mesh is simplified to the point of a few triangles, it exports fine.

**Comment by Semajic** [comment]
Issue Resolved, "Limit to selection" needs to be selected

**Comment by Semajic** [comment]
As an accident above, I did not select an object before exporting, thus the original issue commented still stands.

**Comment by Semajic** [comment]
Additionally, when the polygon count is low enough, it will export. However, the file is corrupted and is unable to be opened by the IM editor

**Comment by rileyzzz** [comment]
Could you send the mesh that's causing the issue?

**Comment by Semajic** [comment]
Sure, here is a zip file with the fbx file and the blender files. The texture that is currently on the mesh is a filler texture, and will be replaced with a proper texture once the issue is resolved
[headlight.zip](https://github.com/rileyzzz/BlenderIMExporter/files/10387939/headlight.zip)

**Comment by rileyzzz** [comment]
Should be fixed now. Seems like your mesh must have been corrupted or something, some of its faces were referencing a non-existent material. I've added a warning that checks for this, you can fix it on the mesh by simply re-assigning the material to all the faces on the mesh in edit mode.
