### ISSUE TITLE
[Request] Export selected only

### ISSUE THREAD

**Issue by adfriz** [rileyzzz/BlenderIMExporter#4]
hello

yesterday, i use this plugin to export mesh to .im format. but when i export it, all the mesh in blend file exported at once.
to export some parts i need to make new blend file and append that mesh from old blend file, that not efficient i think.
because of that i want to request a feature to make an option to export object that selected only/ only active object.

tested with blender 2.83 LTS (2.83.16) and trainz mesh viewer 2 to preview the object.

**Comment by rileyzzz** [comment]
This is already a thing - limit to "Selection Only" in the export window.
