### ISSUE TITLE
Texture get blended with principle base color

### ISSUE THREAD

**Issue by adfriz** [rileyzzz/BlenderIMExporter#5]
when i export a cube with a image texture, the texture get blended with a base color principle bsdf node.

see image below:
![box](https://user-images.githubusercontent.com/76892624/139796721-e023f722-8604-4b40-8072-abe4b0c2193e.png)
![box2](https://user-images.githubusercontent.com/76892624/139796735-59bf096b-385d-45c6-92bc-716c262f2b7c.png)

i use blender 3.0 beta and old trainz mesh viewer

**Comment by rileyzzz** [comment]
Try this again with the latest version

**Comment by adfriz** [comment]
worked, thanks
![e](https://user-images.githubusercontent.com/76892624/141927506-cce895f0-12cf-4ddd-bb9e-684c93a08154.png)
!
